"use strict";
exports.__esModule = true;
var express_1 = require("express");
var users_controller_1 = require("../controllers/users-controller");
var router = express_1["default"].Router();
router.get("/getUser", users_controller_1.getUser);
router.post("/createUser", users_controller_1.createUser);
router.put("/editUser/:id", users_controller_1.editUser);
router.patch("/editInfoUser", users_controller_1.editInfoUser);
router["delete"]("/deleteUser", users_controller_1.deleteUser);
exports["default"] = router;
